# Site settings
title: Orange
# email: [email address] 
description: "Orange is a free Open Source Jekyll theme aimed at simplicity."
avatar_path: "/assets/img/avatar.png"

url: "http://talentedunicorn.github.io/orange"

env: production # - Set 'development' or 'production'
exclude: [node_modules/, .sass-cache/]

sass:
 sass_dir: _sass
 style: compressed

paginate: 5
paginate_path: "blog/:num"

# Build settings
markdown: kramdown
permalink: pretty


# Google Tag manager ID
# tagManagerID: GTM-[ID] # Your tag manager container ID

# Disqus settings
# disqus_shortname: [shortname] # Disqus shortname 

# Contact form post url - Where the form gets posted - Check out brace.io for free form posts http://forms.brace.io/
# formpost: http://forms.brace.io/[email address]
formpost: http://talentedunicorn.github.io/orange # For testing only
